name: eslint 
on: 
  push:
    branches:
      - 'stable'
env:
  ESLINT_CONFIG_URL: https://raw.githubusercontent.com/c4rp1nch0/gh-security-tools/stable/configs/eslint/${{ github.event.repository.name }}.json
  
jobs:
  lint-and-comment-pr:
    name: run eslint and comment the pr
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout this repository
        uses: actions/checkout@v3
      
      - name: Download eslint config
        run: |
          ESLINTRC="$(mktemp -d)/eslintrc.json"
          curl -LfsS ${{ env.ESLINT_CONFIG_URL }} -H "Authorization: token ${{ secrets.GH_SECURITY_TOKEN }}" -o $ESLINTRC
          echo "::set-env name=ESLINTRC::$ESLINTRC"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Run eslint and reviewdog
        run: docker run --rm -v $ESLINTRC:/home/node/scan/eslintrc.json -v $PWD:/home/node/src c4rp1nch0/security-tools-eslint sh -c 'eslint --no-eslintrc -c /home/node/scan/eslintrc.json --ext .ts,.tsx,.js,.jsx,.json --no-color --format rdjson --no-error-on-unmatched-pattern --no-inline-config /home/node/src | reviewdog -f=rdjson -reporter=github-pr-review -fail-on-error'

