on: 
  push:
    branches:
      - 'stable' 
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]
    branches:
      - 'stable'

jobs:
  test-private-action:
    runs-on: ubuntu-latest
    name: Eslint Runner 
    steps:

      - name: Checkout this repo 
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Checkout private actions
        uses: actions/checkout@v3
        with:
          repository: c4rp1nch0/security-actions
          token: ${{ secrets.GH_SECURITY_TOKEN }}
          path: .github/security-actions

      - name: Get tinted files 
        id: tinted-files
        uses: ./.github/security-actions/tinted-files
      - name: list files
        run: |
          echo ${{ steps.tinted-files.outputs.tinted-files}}
          for file in ${{ steps.tinted-files.outputs.tinted-files}}; do
            echo "* $file"
          done

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Run eslint 
        uses: ./.github/security-actions/eslint-reviewdog
        with:
          eslint-config-name: 'default.json'
          eslint-flags: '--no-color --no-error-on-unmatched-pattern --no-inline-config' 
          eslint-paths: ${{ steps.tinted-files.outputs.tinted-files }}
          reviewdog-filter-mode: added

