on: 
  push:
    branches:
      - 'stable' 
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]
    branches:
      - 'stable'

env:
  ESLINT_CONFIG_URL: https://raw.githubusercontent.com/c4rp1nch0/gh-security-tools/stable/configs/eslint/${{ github.event.repository.name }}.json

jobs:
  test-private-action:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:

      - name: Checkout this repo 
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          
      - name: Checkout private action
        uses: actions/checkout@v3
        with:
          repository: c4rp1nch0/security-actions
          token: ${{ secrets.GH_SECURITY_TOKEN }}
          path: .github/security-actions
            
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Download eslint config
        id: eslintrc
        run: |
          ESLINTRC=$(mktemp -p ${{ github.workspace }}).json
          curl -LfsS ${{ env.ESLINT_CONFIG_URL }} -H "Authorization: token ${{ secrets.GH_SECURITY_TOKEN }}" -o $ESLINTRC
          echo "::set-output name=eslintrc-path::${ESLINTRC}" 
          
      - name: Run private action 
        uses: ./.github/security-actions/eslint-reviewdog
        with:
          eslint-config-name: 'default.json'
          eslint-flags: '--no-color --no-error-on-unmatched-pattern --no-inline-config' 
          reviewdog-filter-mode: added
