on: 
  push:
    branches:
      - 'stable' 
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]
    branches:
      - 'stable'

jobs:
  test-private-action:
    runs-on: ubuntu-latest
    name: Eslint Runner 
    steps:

      - name: Checkout this repo 
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get tinted files 
        id: tinted-files
        uses: c4rp1nch0/public-action/tinted-files@main

      - name: Run public action 
        uses: c4rp1nch0/public-action/eslint-rd@main
        with: 
          registry-username: ${{ secrets.DOCKER_HUB_USERNAME }}
          registry-password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          eslint-paths: ${{ steps.tinted-files.outputs.tinted-files }} 


