on: [push]

jobs:
  test-private-action:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout private action
        uses: actions/checkout@v3
        with:
          repository: c4rp1nch0/security-actions
          token: ${{ secrets.GH_SECURITY_TOKEN }}
          path: .github/security-actions
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Run private action 
        uses: ./.github/security-actions/eslint-reviewdog
      # Use the output from the `hello` step
