on: 
  push:
    branches:
      - 'stable' 
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]
    branches:
      - 'stable'

env:
  ESLINT_CONFIG_URL: https://raw.githubusercontent.com/c4rp1nch0/gh-security-tools/stable/configs/eslint/${{ github.event.repository.name }}.json

jobs:
  test-private-action:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:

      - name: Checkout this repo 
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          ref: ${{ github.ref }}
          set-safe-directory: /github/workspace 

      - name: Checkout private action
        uses: actions/checkout@v3
        with:
          repository: c4rp1nch0/security-actions
          token: ${{ secrets.GH_SECURITY_TOKEN }}
          path: .github/security-actions
            
      - name: Get changed files 
        run: |
          if [ ${{ github.event_name }} == 'push' ]; then
              git diff --name-only ${{ github.event.before }}..${{ github.event.after }} 
          else
              git diff --name-only ${{ github.sha }}  
          fi


            #      - name: Login to Docker Hub
            #        uses: docker/login-action@v1
            #        with:
            #          username: ${{ secrets.DOCKER_HUB_USERNAME }}
            #          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            #
            #      - name: Run private action 
            #        uses: ./.github/security-actions/eslint-reviewdog
            #        with:
            #          eslint-config-name: 'default.json'
            #          eslint-flags: '--no-color --no-error-on-unmatched-pattern --no-inline-config' 
            #          reviewdog-filter-mode: added
