on: 
  push:
    branches:
      - 'stable' 
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]
    branches:
      - 'stable'

jobs:
  test-private-action:
    runs-on: ubuntu-latest
    name: Eslint Runner 
    steps:

      - name: Checkout this repo 
        uses: actions/checkout@v3
        with:
          fetch-depth: 2


      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Cat github_env
        run: |
          cat "${GITHUB_ENV}"
      - name: Run public action 
        uses: c4rp1nch0/public-action@main
        with: 
          registry-username: ${{ secrets.DOCKER_HUB_USERNAME }}
          registry-password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}


